### DISCUSSION TITLE
Install problem MiKTeX under GitHub Actions

### DISCUSSION THREAD

**Discussion by albert-github** [MiKTeX/miktex#1204] [Q&A] [answered]
I asked this also as https://stackoverflow.com/questions/74111130/install-problem-miktex-under-github-actions but got no response 😞 ), so trying it here as well.

Since around October 16 2022 we have problems with installing MiKTeX under GitHub Actions.
The error we get is:
```
Run ./miktexsetup_standalone --local-package-repository=C:/miktex-repository \
  ./miktexsetup_standalone --local-package-repository=C:/miktex-repository \
                --package-set=essential \
                --shared \
                install
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
initexmf.exe: The executed process did not succeed.
initexmf.exe: Data: fileName="C:\Program Files\MiKTeX\miktex\bin\x64\initexmf.exe", exitCode="1"
Error: Process completed with exit code 1.
```

The procedure followed in GitHub Actions consists of a few steps:

Step 1:
====
```
    - name: Download MikTex (Windows)
      run: |
        $wc = New-Object System.Net.WebClient;
        $maxAttempts=5;
        $attemptCount=0;
        Do {
          $attemptCount++;
          Try {
            $wc.DownloadFile("https://ctan.math.illinois.edu/systems/win32/miktex/setup/windows-x64/miktexsetup-5.1-x64.zip","miktexsetup-5.1-x64.zip")
          } Catch [Exception] {
            Write-Host $_.Exception | format-list -force
          }
        } while (((Test-Path "miktexsetup-5.1-x64.zip") -eq $false) -and ($attemptCount -le $maxAttempts))
      shell: pwsh
      if: matrix.config.os == 'windows-latest'
```
Step 2:
====
```
    - name: Extract MikTex zip (Windows)
      shell: bash
      run: |
        unzip miktexsetup-5.1-x64.zip
      if: matrix.config.os == 'windows-latest'
```
Step 3:
====
```
    - name: Download MikTex packages (Windows)
      shell: bash
      run: |
        ./miktexsetup_standalone --verbose \
                      --local-package-repository=C:/miktex-repository \
                      --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" \
                      --package-set=essential \
                      download
      if: matrix.config.os == 'windows-latest'

```
Step 4 (the failing step):
====
```
    - name: Install MikTex packages (Windows)
      shell: bash
      run: |
        ./miktexsetup_standalone --local-package-repository=C:/miktex-repository \
                      --package-set=essential \
                      --shared \
                      install
      if: matrix.config.os == 'windows-latest'

```
Step 5:
====
```
    - name: Setting MikTex paths (Windows)
      shell: bash
      run: |
        echo "C:/Program Files/MiKTeX/miktex/bin/x64/" >> $GITHUB_PATH
        export PATH="/c/Program Files/MiKTeX/miktex/bin/x64/:$PATH"

        echo "Configuring MiKTeX to install missing packages on the fly"
        initexmf --admin --verbose --set-config-value='[MPM]AutoInstall=1'
      if: matrix.config.os == 'windows-latest'
```

Any ideas how to solve this problem / what can be the problem?

**Comment by albert-github** [comment]
A new test with:
```
Run ./miktexsetup_standalone --local-package-repository="C:/miktex-repository" \
  ./miktexsetup_standalone --local-package-repository="C:/miktex-repository" \
                --verbose \
                --package-set=essential \
                --shared \
                install
```

Results in:

```
extracting files from miktex-zzip-bin-x64-2.9.tar.lzma...
extracting files from tetex.tar.lzma...
updating package manifests ("C:\Program Files\MiKTeX\miktex/config\package-manifests.ini")...
installed 6039 package manifests
visiting repository C:/miktex-repository...
repository type: local package repository
loading package repository manifest...
initexmf.exe: The executed process did not succeed.

initexmf.exe: Data: fileName="C:\Program Files\MiKTeX\miktex\bin\x64\initexmf.exe", exitCode="1"

Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:



  --log-file=C:\Program Files\MiKTeX\miktex/config\uninst.log: unknown option



The log file hopefully contains the information to get MiKTeX going again:



  C:\ProgramData\MiKTeX\miktex\log\initexmf_admin.log

Error: Process completed with exit code 1.
```

**Comment by albert-github** [comment]
Created an issue from this: https://github.com/MiKTeX/miktex/issues/1213

**Comment by albert-github** [comment]
From: https://github.com/MiKTeX/miktex/issues/1213#issuecomment-1295156743
(which has been closed for comments)

@edocevoli wrote:
>Sorry, but I cannot help you with this issue.

and in a second comment:
> By the way, you are using an outdated version of the setup utility. I think, that's the culprit.

So it looks like https://ctan.math.illinois.edu is outdated but when looking at https://www.ctan.org/tex-archive/systems/win32/miktex/setup/windows-x64
I find there in both cases a miktexsetup-5.1-x64.zip with the same date and the same md5sum.
I also looked at the packages directory but this looks up to date as well.

In an test (around October 18, 2022) I tried another mirror as well: http://mirror.easyname.at/ctan with the same effect.

So it is for me 100% unclear why this is happening.

**Comment by albert-github** [comment, marked as answer]
@edocevoli wrote in https://github.com/MiKTeX/miktex/issues/1213#issuecomment-1295781432

> I have cleaned up the CTAN directory, i.e., the outdated version is not available anymore. Please adjust your build pipeline and download the latest version.

So replacing the version miktexsetup-5.1-x64.zip by miktexsetup-5.2.0+b8f430f-x64.zip looks like to have solved the issue.

Fortunately his initial remark:
> Sorry, but I cannot help you with this issue.

was not true.

**Comment by koppor** [comment]
Alternative installation way:

```yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MiKTeX
        run: |
          choco install miktex --no-progress
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - run: initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
      - run: miktex --admin --verbose packages update-package-database
      - run: miktex --admin --verbose packages update
      - run: miktex --verbose packages update
      - run: miktex --admin --verbose packages install cm-super
      - run: miktex --admin --verbose fndb refresh
      - run: initexmf --admin --verbose --update-fndb
      - run: initexmf --admin --verbose --mklinks --force
      - run: updmap --admin
      - run: pdflatex mwe.tex
```
