### DISCUSSION TITLE
How to properly check for updates on Linux?

### DISCUSSION THREAD

**Discussion by koppor** [MiKTeX/miktex#1366] [Q&A] [answered]
I get following warning

    miktex-makepk: major issue: So far, you have not checked for MiKTeX updates.

I run following commands after the `apt-get install`:

```
miktex --verbose packages update-package-database
miktex --verbose packages update
miktex --verbose packages update
miktex --verbose packages install cm-super
miktex --verbose fndb refresh
initexmf --verbose --update-fndb
initexmf --verbose --mklinks --force
updmap
pdflatex mwe
```

The last command outputs the error. -- I thought that `packages update` would check for updates. What should be done to have `pdflatex` not outputting the update warning?

Complete script at https://github.com/koppor/mwe-miktex/blob/main/.github/workflows/illustrate-no-update-check.yml.

**Comment by koppor** [comment, marked as answer]
On **Linux (on GitHub actions)**, I need following checks (source: https://github.com/koppor/mwe-miktex/blob/8ccea8a58db2d7c109f7bda39eb9d2ce5d7306e0/.github/workflows/miktex.yml#L45):

```yaml
      - run: miktexsetup --verbose finish
      - run: initexmf --verbose --set-config-value=[MPM]AutoInstall=1
      - run: miktex --verbose packages update-package-database
      - run: miktex --verbose packages update
      - run: miktex --verbose packages install cm-super amsfonts
      - run: miktex --verbose fontmaps configure
      - run: miktex --verbose fndb refresh
      - run: initexmf --verbose --update-fndb
      - run: updmap
```

In **Docker**, it's slightly different, but also works (source: https://github.com/koppor/mwe-miktex/blob/8ccea8a58db2d7c109f7bda39eb9d2ce5d7306e0/Dockerfile#L1) - note the `--admin` at `initexmf --admin --verbose --update-fndb`, which is missing in the GitHub workflow

```Dockerfile
RUN miktexsetup --verbose finish
RUN initexmf --verbose --set-config-value=[MPM]AutoInstall=1
RUN miktex --verbose packages update-package-database
RUN miktex --verbose packages update
RUN miktex --verbose packages install cm-super amsfonts
RUN miktex --verbose fontmaps configure
RUN miktex --verbose fndb refresh
RUN initexmf --admin --verbose --update-fndb
RUN updmap
```

On **Windows (on GitHub actions)**, it's as follows (source: https://github.com/koppor/mwe-miktex/blob/8ccea8a58db2d7c109f7bda39eb9d2ce5d7306e0/.github/workflows/miktex.yml#L84)

```cmd
          initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --admin --verbose packages update-package-database
          miktex --admin --verbose packages update
          miktex --verbose packages update
          miktex --admin --verbose packages install cm-super
          miktex --admin --verbose fndb refresh
          initexmf --admin --verbose --update-fndb
          initexmf --admin --verbose --mklinks --force
          updmap --admin
```
