### ISSUE TITLE
"beuron-otf" seems to be missing

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#612]
I am using [Modern Simple CV](https://github.com/latex-ninja/modern-simple-cv) and get following compilation error when using lualatex (`lualatex main`):

```text
(C:/MiKTeX/tex/latex/beuron/beuron.sty
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not found: Beuron-Regular.otf.".

! Package fontspec Error: The font "Beuron-Regular" cannot be found.

For immediate help type H <return>.
 ...

l.35    }
```

CTAN reports that `Beuron-Regular.otf` is part of [fonts/beuron/fonts](https://ctan.org/tex-archive/fonts/beuron/fonts):

![grafik](https://user-images.githubusercontent.com/1366654/92286130-6d406380-ef06-11ea-9fe9-d70c78705412.png)

In MikTeX, `Beuron*.otf` were not packaged: <https://miktex.org/packages/beuron/files> does not list any `.otf` file.

For Libertinus, there seems to be a separate `-otf` package:

![grafik](https://user-images.githubusercontent.com/1366654/92286241-c1e3de80-ef06-11ea-94d9-f9e14ac99a00.png)

For Beuron, there is no `-otf` package:

![grafik](https://user-images.githubusercontent.com/1366654/92286281-dc1dbc80-ef06-11ea-8c2b-1b92bdbdabe2.png)

I suggest that "simply" the package "beuron-otf" is missing. Maybe, I am overlooking something?

## `initexmf --report`

```yaml
ReportDate: 2020-09-04 23:27:44
CurrentVersion: 20.7
SetupDate: 2020-09-03 11:45:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: d26133b / 2020-07-31 18:20:50
OS: Windows 10 Pro, 64-bit, build 20150
SharedSetup: no
LinkTargetDirectory: C:\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-09-04 23:21:03
LastUpdate: 2020-09-04 23:19:01
LastUpdateDb: 2020-09-04 23:21:02
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\koppor\AppData\Roaming\MiKTeX
Root1: C:\Users\koppor\AppData\Local\MiKTeX
Root2: C:\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\MiKTeX
UserConfig: C:\Users\koppor\AppData\Roaming\MiKTeX
UserData: C:\Users\koppor\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
```
